production:
  adapter: postgresql
  database: redmine
  host: db_prod
  username: redmine
  password: "redmine"
  encoding: utf8
  schema_search_path: public
  
development:
  adapter: postgresql
  database: redmine
  host: db_dev
  username: redmine
  password: "redmine"
  encoding: utf8
  schema_search_path: public

test:
  adapter: postgresql
  database: redmine
  host: db_test
  username: redmine
  password: "redmine"
  encoding: utf8
  schema_search_path: public