version: '3'
services:
  db_prod: 
    build:
      context: .
      dockerfile: Dockerfile.db.prod
    environment:
      POSTGRES_PASSWORD: redmine

  db_test: 
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: redmine
      POSTGRES_USER: redmine
      POSTGRES_DB: redmine

  redmine:
    build:
      context: .
    depends_on:
      - db_test
      - db_prod
    ports:
      - 127.0.0.1:3000:3000
